### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by GULPF** [Durlek/CommunicationInterface#2]
Gick igenom HttpClient och hittade lite saker som behöver ändras.
#### #testConnection

Det är responskroppen som skall vara 123, inte statuskoden.
#### #sendPost

Sensors id står inte i responskroppen, utan i location header. Kollade lite snabbt i Javaklassen du använder och denna metod borde gå att använda (ligger i en klass som HttpURLConnection ärver ifrån): http://download.java.net/jdk7/archive/b123/docs/api/java/net/URLConnection.html#getHeaderFields()
#### Felhantering

Hade varit bra med lite mer felhantering, till exempel bör #sendGet, #sendPut & #sendDelete throwa om statuskoden är 404.
#### Exempel på sensor-objekt (LCD)

``` Javascript{
{
    Data: [
        {
            BarCount: 5
        ,   VolumeConcentration: 20
        ,   SubstanceIndex: 0
        }
    ]
,   Id: <något id>
,   Position: {Altitude: 0, Latitude: 1, Longitude: 2}
,   State: {
        AudioFault:             true
    ,   CRAboveLimit:           false
    ,   ChangeBattery:          false
    ,   ChangeSievePack:        false
    ,   CodeChecksumError:      false
    ,   CoronaBurnOff:          false
    ,   EEPROMChecksumError:    false
    ,   FanCAboveLimit:         false
    ,   FatalError:             false
    ,   GAlert:                 false
    ,   GHighDoseAlert:         false
    ,   GMediumDoseAlert:       false
    ,   HAlert:                 false
    ,   HHighDoseAlert:         false
    ,   HTOutSideLimits:        false
    ,   HealthCheckFailure:     false
    ,   InitialSelfTest:        false
    ,   InitialSelfTestFailure: false
    ,   LowBattery:             false
    ,   LowSieve:               false
    ,   PTOutOfRange:           false
    ,   TICAlert:               false
    ,   TICMode:                false
    }
}
```

**Comment by Durlek** [comment]
Nice. Bra feedback.

Frågor angående sensordatan:
I tex Data och State, är det en array med strings som: "BarCount: 5" eller är det json Key och Value typ? är lite osäker här.

Date: Wed, 25 Nov 2015 06:17:01 -0800

**Comment by GULPF** [comment]
Data är en JSON-array som består av JSON key/value objekt, State är bara ett stort JSON key/value objekt.

**Comment by Durlek** [comment]
{
    "Data": [{
        "BarCount": 5,
        "VolumeConcentration": 20,
        "SubstanceIndex": 0
    }],
    "Id": "abc",
    "Position": {
        "Altitude": 0,
        "Latitude": 1,
        "Longitude": 2
    },
    "State": {
        "AudioFault": true,
        "CRAboveLimit": false,
        "ChangeBattery": false,
        "ChangeSievePack": false,
        "CodeChecksumError": false,
        "CoronaBurnOff": false,
        "EEPROMChecksumError": false,
        "FanCAboveLimit": false,
        "FatalError": false
    }
}
