### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by dat13jni** [Durlek/CommunicationInterface#8]
Om testConnection()-metoden i HttpClient anropas från ConnectionTester-klassens test(String uri)-metod med en tom sträng, kommer det att throwas en IllegalArgumentException ("protocol = http host = null").

Detta bör fixas genom att man catchar exceptionen i testConnection()-metoden.

rad 34: catch (IOException e) bör ändras till catch(IOExcetion | IllegalArgumentException e)

Detta kan betyda att samma exception kan throwas från de andra metoderna men jag är inte säker om det är möjligt.

**Comment by GULPF** [comment]
Solved in pull request
